const KEY='flowdesk_leads_v2',SETTINGS='flowdesk_settings_v2';let leads=JSON.parse(localStorage.getItem(KEY)||'[]');let settings=JSON.parse(localStorage.getItem(SETTINGS)||'{}');
const $=id=>document.getElementById(id);function save(){localStorage.setItem(KEY,JSON.stringify(leads));render()}function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function render(){const counts=['new','contacted','booked','completed'];counts.forEach(s=>$(s==='new'?'mNew':'m'+s[0].toUpperCase()+s.slice(1)).textContent=leads.filter(x=>x.status===s).length);$('today').textContent=new Date().toLocaleDateString('en-RW',{day:'numeric',month:'short',year:'numeric'});const list=$('leadList');if(!leads.length){list.innerHTML='<div class="empty"><h3>No leads yet</h3><p>Real enquiries submitted below will appear here.</p></div>';return}list.innerHTML=leads.map(l=>'<article class="lead"><div><h3>'+esc(l.name)+'</h3><p>'+esc(l.phone)+' · '+esc(l.service)+(l.datetime?' · '+esc(l.datetime):'')+'</p>'+(l.message?'<small>'+esc(l.message)+'</small>':'')+'</div><div class="lead-actions"><a class="wa" target="_blank" href="'+waLink(l)+'">WhatsApp</a><select onchange="statusChange(\''+l.id+'\',this.value)">'+['new','contacted','booked','completed','lost'].map(s=>'<option '+(l.status===s?'selected':'')+' value="'+s+'">'+s+'</option>').join('')+'</select></div></article>').join('');const act=$('activity');act.innerHTML=leads.slice(0,6).map(l=>'<div class="activity"><span>✦</span><div><p>'+esc(l.name)+' · '+esc(l.status)+'</p><small>'+new Date(l.created).toLocaleString()+'</small></div></div>').join('')||'<div class="empty"><p>Actions will appear here.</p></div>'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function waLink(l){let n=(settings.whatsapp||'').replace(/\D/g,'');if(n&&!n.startsWith('250'))n='250'+n;let msg=encodeURIComponent((settings.followup||'Hello {name}, thanks for contacting us.').replaceAll('{name}',l.name)+'\n\nRequest: '+l.service);return n?'https://wa.me/'+n+'?text='+msg:'https://wa.me/?text='+msg}
function statusChange(id,status){const l=leads.find(x=>x.id===id);if(l){l.status=status;l.updated=Date.now();save();toast('Lead updated ✓')}}
$('leadForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const lead={id:crypto.randomUUID(),name:f.get('name'),phone:f.get('phone'),service:f.get('service'),datetime:f.get('datetime'),message:f.get('message'),status:'new',created:Date.now(),updated:Date.now()};leads.unshift(lead);save();e.currentTarget.reset();$('formMessage').textContent='✓ Lead saved. It is now in the live queue.';toast('New lead saved ✓');setTimeout(()=>$('formMessage').textContent='',2500)});
function exportCSV(){if(!leads.length)return toast('No leads to export');const rows=[['Name','Phone','Service','Date/Time','Message','Status','Created'],...leads.map(l=>[l.name,l.phone,l.service,l.datetime,l.message,l.status,new Date(l.created).toISOString()])];const csv=rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='flowdesk-leads.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV exported ✓')}
function clearAll(){if(confirm('Delete every lead from this browser workspace?')){leads=[];save();toast('Workspace cleared')}}
function loadSettings(){$('businessName').value=settings.businessName||'';$('whatsapp').value=settings.whatsapp||'';$('followup').value=settings.followup||''}function saveSettings(){settings={businessName:$('businessName').value,whatsapp:$('whatsapp').value,followup:$('followup').value};localStorage.setItem(SETTINGS,JSON.stringify(settings));$('settingsMessage').textContent='Settings saved ✓';toast('Settings saved ✓')}
loadSettings();render();