"use client";
import Link from "next/link";
import {useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {useRouter} from "next/navigation";

export default function Signup(){
 const[e,setE]=useState("");const[m,setM]=useState("");const[loading,setL]=useState(false);const r=useRouter();
 async function go(ev:React.FormEvent<HTMLFormElement>){ev.preventDefault();setL(true);setE("");const f=new FormData(ev.currentTarget);const s=createClient();const{data,error}=await s.auth.signUp({email:String(f.get("email")),password:String(f.get("password")),options:{data:{business_name:String(f.get("business_name")),owner_name:String(f.get("owner_name")),phone:String(f.get("phone")),business_type:String(f.get("business_type")),country:String(f.get("country")),}}});if(error)setE(error.message);else if(data.session)r.push("/dashboard");else setM("Account created. Check your email to confirm it, then log in.");setL(false)}
 return <main className="authPage"><div className="authCard wide"><Link className="brand" href="/">Follow<span>Flow</span></Link><div className="authIntro"><h1>Create your workspace 🚀</h1><p>Just a few details. You can change them later.</p></div>{e&&<div className="error">{e}</div>}{m&&<div className="notice">{m}</div>}<form className="form" onSubmit={go}><div className="twoCol"><div className="field"><label>Your name</label><input name="owner_name" placeholder="Your name" required/></div><div className="field"><label>Business name</label><input name="business_name" placeholder="e.g. ABC Boutique" required/></div><div className="field"><label>Email</label><input name="email" type="email" placeholder="you@business.com" required/></div><div className="field"><label>Phone</label><input name="phone" type="tel" placeholder="+250..." required/></div><div className="field"><label>Business type</label><select name="business_type" defaultValue="Other"><option>Retail</option><option>Restaurant</option><option>Hotel</option><option>Salon & Beauty</option><option>Professional Services</option><option>Real Estate</option><option>Other</option></select></div><div className="field"><label>Country</label><input name="country" defaultValue="Rwanda" required/></div></div><div className="field"><label>Password</label><input name="password" type="password" minLength={8} placeholder="At least 8 characters" required/></div><button className="btn primary" disabled={loading}>{loading?"Creating workspace…":"Create my free workspace"}</button></form><p className="authBottom">Already have an account? <Link href="/login">Log in</Link></p></div></main>
}