"use client";
import {useEffect,useState} from "react";import {useSearchParams} from "next/navigation";import Link from "next/link";import {createClient} from "@/lib/supabase/client";
const statuses=["new","contacted","interested","follow-up","won","lost"];const sources=["WhatsApp","Instagram","Facebook","Phone","Website","Walk-in","Referral","Other"];
export default function Leads(){const s=createClient(),params=useSearchParams();const[rows,setRows]=useState<any[]>([]),[bid,setBid]=useState(""),[q,setQ]=useState(""),[filter,setFilter]=useState("all"),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[err,setErr]=useState("");
 async function load(){const{data:{user}}=await s.auth.getUser();if(!user)return;const{data:b}=await s.from("businesses").select("id").eq("owner_id",user.id).single();if(!b)return setErr("Business workspace not found.");setBid(b.id);const{data,error}=await s.from("leads").select("*").eq("business_id",b.id).order("created_at",{ascending:false});if(error)setErr(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[]);useEffect(()=>{if(params.get("new")==="1"){setEdit(null);setOpen(true)}},[params]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const p={business_id:bid,name:String(f.get("name")).trim(),phone:String(f.get("phone")).trim(),email:String(f.get("email")||"").trim()||null,source:String(f.get("source")),status:String(f.get("status")),notes:String(f.get("notes")||"").trim()||null,next_follow_up:f.get("next_follow_up")?new Date(String(f.get("next_follow_up"))).toISOString():null,estimated_value:f.get("estimated_value")?Number(f.get("estimated_value")):null};const r=edit?await s.from("leads").update(p).eq("id",edit.id).eq("business_id",bid):await s.from("leads").insert(p);if(r.error)setErr(r.error.message);else{setOpen(false);setEdit(null);await load()}}
 async function del(id:string){if(!confirm("Delete this lead? This cannot be undone."))return;await s.from("leads").delete().eq("id",id).eq("business_id",bid);load()}
 const shown=rows.filter(x=>(filter==="all"||x.status===filter)&&[x.name,x.phone,x.email,x.source].join(" ").toLowerCase().includes(q.toLowerCase()));
 return <><div className="pageIntro"><div><div className="eyebrow">CUSTOMERS</div><h1>Your leads</h1><p>Everyone who may become a customer.</p></div><button className="btn primary" onClick={()=>{setEdit(null);setOpen(true)}}>+ Add lead</button></div>
 <div className="toolbar"><input className="search" placeholder="Search by name, phone or source…" value={q} onChange={e=>setQ(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All leads</option>{statuses.map(x=><option key={x} value={x}>{x.replace("-"," ")}</option>)}</select></div>{err&&<div className="error">{err}</div>}
 {shown.length===0?<div className="card empty"><div className="emptyIcon">⌕</div><h3>{rows.length?"No leads match your search.":"No leads yet."}</h3><p>{rows.length?"Try another search or filter.":"Add your first customer inquiry to get started."}</p>{!rows.length&&<button className="btn primary" onClick={()=>setOpen(true)}>Add a lead</button>}</div>:<div className="leadTable card"><div className="tableScroll"><table><thead><tr><th>Customer</th><th>Source</th><th>Status</th><th>Next follow-up</th><th></th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><Link href={"/dashboard/leads/"+x.id}><strong>{x.name}</strong></Link><small>{x.phone}</small></td><td>{x.source}</td><td><span className={"status "+x.status}>{x.status.replace("-"," ")}</span></td><td>{x.next_follow_up?new Date(x.next_follow_up).toLocaleString():"Not scheduled"}</td><td><button className="mini" onClick={()=>{setEdit(x);setOpen(true)}}>Edit</button><button className="mini dangerText" onClick={()=>del(x.id)}>Delete</button></td></tr>)}</tbody></table></div></div>}
 {open&&<div className="modal"><div className="modalBox"><div className="modalHead"><div><h2>{edit?"Edit lead":"Add a new lead"}</h2><p>It only takes a few seconds.</p></div><button className="close" onClick={()=>setOpen(false)}>×</button></div><form className="form" onSubmit={save}><div className="twoCol"><div className="field"><label>Customer name</label><input name="name" defaultValue={edit?.name||""} placeholder="e.g. Jean Paul" required/></div><div className="field"><label>Phone / WhatsApp</label><input name="phone" defaultValue={edit?.phone||""} placeholder="+250..." required/></div><div className="field"><label>Email <span className="optional">optional</span></label><input name="email" type="email" defaultValue={edit?.email||""} placeholder="customer@email.com"/></div><div className="field"><label>Where did they come from?</label><select name="source" defaultValue={edit?.source||"WhatsApp"}>{sources.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>What stage?</label><select name="status" defaultValue={edit?.status||"new"}>{statuses.map(x=><option key={x}>{x.replace("-"," ")}</option>)}</select></div><div className="field"><label>Estimated value <span className="optional">optional</span></label><input name="estimated_value" type="number" min="0" defaultValue={edit?.estimated_value||""} placeholder="RWF"/></div><div className="field"><label>Next follow-up <span className="optional">optional</span></label><input name="next_follow_up" type="datetime-local" defaultValue={edit?.next_follow_up?new Date(edit.next_follow_up).toISOString().slice(0,16):""}/></div></div><div className="field"><label>Notes <span className="optional">optional</span></label><textarea name="notes" rows={3} defaultValue={edit?.notes||""} placeholder="What did the customer ask for?"/></div><button className="btn primary">{edit?"Save changes":"Save lead"}</button></form></div></div>}</>
}